triggering:
  events:                       # List the events that trigger builds
    - push
    - pull_request
    - tag
  branch_patterns:              # Include or exclude watched branches
    - pattern: '*'
      include: true
      source: true
    - pattern: excluded-target
      include: false
      source: false
    - pattern: included-source
      include: true
      source: true
  tag_patterns:                 # Include or exlude watched tag labels
    - pattern: '*'
      include: true
    - pattern: excluded-tag
      include: false
    - pattern: included-tag
      include: true
  cancel_previous_builds: true  # Automatically cancel outdated webhook builds

workflows:cluded-targ
  hello-world:
    name: Hello world workflow
    scripts:
        - echo "Hello World!"
    when:
      changeset:
        includes:
          - '.'
        excludes:
          - '**/*.md'
